title: "Great Minds"
sections:
  1: Color Swatches
  2: Responsive Grid
  3: Typography
  4: Iconography
  5: Buttons
  6: Forms
  7: Tables
  8: Alerts
  9: Navigation
  10: Pagination
  11: Badges
  12: Jumbotron
  13: Thumbnails
  14: List group
  15: Panels
  16: Wells
  17: Modal
  18: Cards
