---
- :name: Role/Curriculum Selector Hero
  :fields:
  - :name: background_image_url
    :label: Background Image Url
    :input_type: text
  - :name: background_image_2_url
    :label: Background Image 2 Url (optional)
    :input_type: text
  - :name: background_image_3_url
    :label: Background Image 3 Url (optional)
    :input_type: text
  - :name: title
    :label: Title
    :input_type: text
  - :name: title_highlight
    :label: Title Highlight
    :input_type: text

- :name: Testimonials (Header, image, text, link)
  :fields:
    - :name: testimonial_header
      :label: Header
      :input_type: text
    - :name: testimonial_image_url
      :label: Image url
      :input_type: text
    - :name: testimonial_text
      :label: Text
      :input_type: text
    - :name: testimonial_link_url
      :label: Link Url
      :input_type: text
    - :name: testimonial_link_text
      :label: Link Text
      :input_type: text

- :name: Testimonials (Header, video, text)
  :fields:
    - :name: testimonial_header_2
      :label: Header
      :input_type: text
    - :name: testimonial_video_url_2
      :label: Video link
      :input_type: text
    - :name: testimonial_text_2
      :label: Text
      :input_type: text

- :name: Video Hero
  :fields:
  - :name: title
    :label: Title
    :input_type: text
  - :name: wistia_video_id
    :label: Wistia Video Id
    :input_type: text
  - :name: background_image_url
    :label: Background Image Url (optional)
    :input_type: text
  - :name: background_color
    :label: Background Color
    :input_type: select
    :input_options:
      - green
      - blue
      - cream
      - orange
      - light-blue
- :name: 50/50 Full-Bleed Image Left
  :fields:
  - :name: title
    :label: Title
    :input_type: text
  - :name: body_text
    :label: Body Text
    :input_type: text_area
  - :name: background_color
    :label: Background Color
    :input_type: select
    :input_options:
      - green
      - blue
      - cream
      - orange
      - light-blue
  - :name: button_1_title
    :label: Button 1 Title
    :input_type: text
  - :name: button_1_link
    :label: Button 1 Link
    :input_type: text
  - :name: button_1_target
    :label: Button 1 Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: button_2_title
    :label: Button 2 Title
    :input_type: text
  - :name: button_2_link
    :label: Button 2 Link
    :input_type: text
  - :name: button_2_target
    :label: Button 2 Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: image_url
    :label: Image Url
    :input_type: text
  - :name: alt_text
    :label: Image Alt Text
    :input_type: text
- :name: 50/50 Full-Bleed Image Left, Half Height
  :fields:
  - :name: title
    :label: Title
    :input_type: text
  - :name: body_text
    :label: Body Text
    :input_type: text_area
  - :name: background_color
    :label: Background Color
    :input_type: select
    :input_options:
      - green
      - blue
      - cream
      - orange
      - light-blue
  - :name: button_title
    :label: Button Title
    :input_type: text
  - :name: button_link
    :label: Button Link
    :input_type: text
  - :name: button_target
    :label: Button Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: image_url
    :label: Image Url
    :input_type: text
  - :name: alt_text
    :label: Image Alt Text
    :input_type: text
- :name: 50/50 Full-Bleed Image Right
  :fields:
  - :name: title
    :label: Title
    :input_type: text
  - :name: body_text
    :label: Body Text
    :input_type: text_area
  - :name: background_color
    :label: Background Color
    :input_type: select
    :input_options:
      - green
      - blue
      - cream
      - orange
      - light-blue
  - :name: button_1_title
    :label: Button 1 Title
    :input_type: text
  - :name: button_1_link
    :label: Button 1 Link
    :input_type: text
  - :name: button_1_target
    :label: Button 1 Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: button_2_title
    :label: Button 2 Title
    :input_type: text
  - :name: button_2_link
    :label: Button 2 Link
    :input_type: text
  - :name: button_2_target
    :label: Button 2 Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: image_url
    :label: Image Url
    :input_type: text
  - :name: alt_text
    :label: Image Alt Text
    :input_type: text
- :name: 50/50 Full-Bleed Image Right, Half Height
  :fields:
  - :name: title
    :label: Title
    :input_type: text
  - :name: body_text
    :label: Body Text
    :input_type: text_area
  - :name: background_color
    :label: Background Color
    :input_type: select
    :input_options:
      - green
      - blue
      - cream
      - orange
      - light-blue
  - :name: button_title
    :label: Button Title
    :input_type: text
  - :name: button_link
    :label: Button Link
    :input_type: text
  - :name: button_target
    :label: Button Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: image_url
    :label: Image Url
    :input_type: text
  - :name: alt_text
    :label: Image Alt Text
    :input_type: text
- :name: 50/50 Content Image Left
  :fields:
  - :name: title
    :label: Title
    :input_type: text
  - :name: body_text
    :label: Body Text
    :input_type: text_area
  - :name: background_color
    :label: Background Color
    :input_type: select
    :input_options:
      - green
      - blue
      - cream
      - orange
      - light-blue
  - :name: button_title
    :label: Button Title
    :input_type: text
  - :name: button_link
    :label: Button Link
    :input_type: text
  - :name: button_target
    :label: Button Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: image_url
    :label: Image Url
    :input_type: text
  - :name: alt_text
    :label: Image Alt Text
    :input_type: text
- :name: 50/50 Content Image Left, Half Height
  :fields:
  - :name: title
    :label: Title
    :input_type: text
  - :name: body_text
    :label: Body Text
    :input_type: text_area
  - :name: background_color
    :label: Background Color
    :input_type: select
    :input_options:
      - green
      - blue
      - cream
      - orange
      - light-blue
  - :name: button_title
    :label: Button Title
    :input_type: text
  - :name: button_link
    :label: Button Link
    :input_type: text
  - :name: button_target
    :label: Button Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: image_url
    :label: Image Url
    :input_type: text
  - :name: alt_text
    :label: Image Alt Text
    :input_type: text
- :name: 50/50 Content Image Right
  :fields:
  - :name: title
    :label: Title
    :input_type: text
  - :name: body_text
    :label: Body Text
    :input_type: text_area
  - :name: background_color
    :label: Background Color
    :input_type: select
    :input_options:
      - green
      - blue
      - cream
      - orange
      - light-blue
  - :name: button_title
    :label: Button Title
    :input_type: text
  - :name: button_link
    :label: Button Link
    :input_type: text
  - :name: button_target
    :label: Button Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: image_url
    :label: Image Url
    :input_type: text
  - :name: alt_text
    :label: Image Alt Text
    :input_type: text
- :name: 50/50 Content Image Right, Half Height
  :fields:
  - :name: title
    :label: Title
    :input_type: text
  - :name: body_text
    :label: Body Text
    :input_type: text_area
  - :name: background_color
    :label: Background Color
    :input_type: select
    :input_options:
      - green
      - blue
      - cream
      - orange
      - light-blue
  - :name: button_title
    :label: Button Title
    :input_type: text
  - :name: button_link
    :label: Button Link
    :input_type: text
  - :name: button_target
    :label: Button Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: image_url
    :label: Image Url
    :input_type: text
  - :name: alt_text
    :label: Image Alt Text
    :input_type: text
- :name: 50/50 Content Image Shadow Left
  :fields:
  - :name: title
    :label: Title
    :input_type: text
  - :name: body_text
    :label: Body Text
    :input_type: text_area
  - :name: background_color
    :label: Background Color
    :input_type: select
    :input_options:
      - green
      - blue
      - cream
      - orange
      - light-blue
  - :name: button_title
    :label: Button Title
    :input_type: text
  - :name: button_link
    :label: Button Link
    :input_type: text
  - :name: button_target
    :label: Button Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: image_url
    :label: Image Url
    :input_type: text
  - :name: alt_text
    :label: Image Alt Text
    :input_type: text
- :name: 50/50 Content Image Shadow Right
  :fields:
  - :name: title
    :label: Title
    :input_type: text
  - :name: body_text
    :label: Body Text
    :input_type: text_area
  - :name: background_color
    :label: Background Color
    :input_type: select
    :input_options:
      - green
      - blue
      - cream
      - orange
      - light-blue
  - :name: button_title
    :label: Button Title
    :input_type: text
  - :name: button_link
    :label: Button Link
    :input_type: text
  - :name: button_target
    :label: Button Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: image_url
    :label: Image Url
    :input_type: text
  - :name: alt_text
    :label: Image Alt Text
    :input_type: text
- :name: 50/50 Content Image Book Left
  :fields:
  - :name: title
    :label: Title
    :input_type: text
  - :name: body_text
    :label: Body Text
    :input_type: text_area
  - :name: background_color
    :label: Background Color
    :input_type: select
    :input_options:
      - green
      - blue
      - cream
      - orange
      - light-blue
  - :name: button_title
    :label: Button Title
    :input_type: text
  - :name: button_link
    :label: Button Link
    :input_type: text
  - :name: button_target
    :label: Button Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: image_url
    :label: Image Url
    :input_type: text
  - :name: alt_text
    :label: Image Alt Text
    :input_type: text
- :name: 50/50 Content Image Book Right
  :fields:
  - :name: title
    :label: Title
    :input_type: text
  - :name: body_text
    :label: Body Text
    :input_type: text_area
  - :name: background_color
    :label: Background Color
    :input_type: select
    :input_options:
      - green
      - blue
      - cream
      - orange
      - light-blue
  - :name: button_title
    :label: Button Title
    :input_type: text
  - :name: button_link
    :label: Button Link
    :input_type: text
  - :name: button_target
    :label: Button Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: image_url
    :label: Image Url
    :input_type: text
  - :name: alt_text
    :label: Image Alt Text
    :input_type: text
- :name: Image Background, Full Width Text
  :fields:
  - :name: black_overlay
    :label: Black Overlay
    :input_type: checkbox
  - :name: title
    :label: Title
    :input_type: text
  - :name: body_text
    :label: Body Text
    :input_type: text_area
  - :name: button_title
    :label: Button Title
    :input_type: text
  - :name: button_link
    :label: Button Link
    :input_type: text
  - :name: button_target
    :label: Button Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: image_url
    :label: Image Url
    :input_type: text
  - :name: alt_text
    :label: Image Alt Text
    :input_type: text
- :name: Image Background, Full Width Text, Half Height
  :fields:
  - :name: black_overlay
    :label: Black Overlay
    :input_type: checkbox
  - :name: title
    :label: Title
    :input_type: text
  - :name: body_text
    :label: Body Text
    :input_type: text_area
  - :name: button_title
    :label: Button Title
    :input_type: text
  - :name: button_link
    :label: Button Link
    :input_type: text
  - :name: button_target
    :label: Button Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: image_url
    :label: Image Url
    :input_type: text
- :name: Image Background, Text Left
  :fields:
  - :name: black_overlay
    :label: Black Overlay
    :input_type: checkbox
  - :name: title
    :label: Title
    :input_type: text
  - :name: body_text
    :label: Body Text
    :input_type: text_area
  - :name: button_title
    :label: Button Title
    :input_type: text
  - :name: button_link
    :label: Button Link
    :input_type: text
  - :name: button_target
    :label: Button Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: image_url
    :label: Image Url
    :input_type: text
- :name: Image Background, Text Right
  :fields:
  - :name: black_overlay
    :label: Black Overlay
    :input_type: checkbox
  - :name: title
    :label: Title
    :input_type: text
  - :name: body_text
    :label: Body Text
    :input_type: text_area
  - :name: button_title
    :label: Button Title
    :input_type: text
  - :name: button_link
    :label: Button Link
    :input_type: text
  - :name: button_target
    :label: Button Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: image_url
    :label: Image Url
    :input_type: text
- :name: Full Width Text
  :fields:
  - :name: title
    :label: Title
    :input_type: text
  - :name: body_text
    :label: Body Text
    :input_type: text_area
  - :name: background_color
    :label: Background Color
    :input_type: select
    :input_options:
      - green
      - blue
      - cream
      - orange
      - light-blue
  - :name: button_title
    :label: Button Title
    :input_type: text
  - :name: button_link
    :label: Button Link
    :input_type: text
  - :name: button_target
    :label: Button Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: button_type
    :label: Button Type
    :input_type: select
    :input_options:
      - Normal
      - Remote
  - :name: button_type
- :name: 2-Column Text
  :fields:
  - :name: background_color_1
    :label: Background Color 1
    :input_type: select
    :input_options:
      - green
      - blue
      - cream
      - orange
      - light-blue
  - :name: title_1
    :label: Title 1
    :input_type: text
  - :name: body_text_1
    :label: Body Text 1
    :input_type: text_area
  - :name: button_title_1
    :label: Button Title 1
    :input_type: text
  - :name: button_link_1
    :label: Button Link 1
    :input_type: text
  - :name: button_target_1
    :label: Button Target 1
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: background_color_2
    :label: Background Color 2
    :input_type: select
    :input_options:
      - green
      - blue
      - cream
      - orange
      - light-blue
  - :name: title_2
    :label: Title 2
    :input_type: text
  - :name: body_text_2
    :label: Body Text 2
    :input_type: text_area
  - :name: button_title_2
    :label: Button Title 2
    :input_type: text
  - :name: button_link_2
    :label: Button Link 2
    :input_type: text
  - :name: button_target_2
    :label: Button Target 2
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
- :name: 2-Column Video Left, Text Right
  :fields:
  - :name: title
    :label: Title
    :input_type: text
  - :name: wistia_video_id
    :label: Wistia Video Id
    :input_type: text
  - :name: background_image_url
    :label: Background Image Url (optional)
    :input_type: text
  - :name: background_color
    :label: Background Color
    :input_type: select
    :input_options:
      - green
      - blue
      - cream
      - orange
      - light-blue
  - :name: body_text
    :label: Body Text
    :input_type: text_area
  - :name: button_title
    :label: Button Title
    :input_type: text
  - :name: button_link
    :label: Button Link
    :input_type: text
  - :name: button_target
    :label: Button Target
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
- :name: 3-Column Text
  :fields:
  - :name: background_color
    :label: Background Color
    :input_type: select
    :input_options:
      - green
      - blue
      - cream
      - orange
      - light-blue
  - :name: title_1
    :label: Title 1
    :input_type: text
  - :name: body_text_1
    :label: Body Text 1
    :input_type: text_area
  - :name: button_title_1
    :label: Button Title 1
    :input_type: text
  - :name: button_link_1
    :label: Button Link 1
    :input_type: text
  - :name: button_target_1
    :label: Button Target 1
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: title_2
    :label: Title 2
    :input_type: text
  - :name: body_text_2
    :label: Body Text 2
    :input_type: text_area
  - :name: button_title_2
    :label: Button Title 2
    :input_type: text
  - :name: button_link_2
    :label: Button Link 2
    :input_type: text
  - :name: button_target_2
    :label: Button Target 2
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
  - :name: title_3
    :label: Title 3
    :input_type: text
  - :name: body_text_3
    :label: Body Text 3
    :input_type: text_area
  - :name: button_title_3
    :label: Button Title 3
    :input_type: text
  - :name: button_link_3
    :label: Button Link 3
    :input_type: text
  - :name: button_target_3
    :label: Button Target 3
    :input_type: select
    :input_options:
      - Open in Same Tab
      - Open in New Tab
